name: natives

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            cares: false
            artifact_classifier: windows
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            cares: true
            artifact_classifier: linux
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Install c-ares
      if: ${{ matrix.cares }}
      run: |
        cd $(mktemp -d)
        sudo wget -c http://archive.ubuntu.com/ubuntu/pool/main/c/c-ares/libc-ares2_1.18.1-2ubuntu0.1_amd64.deb
        sudo wget -c http://archive.ubuntu.com/ubuntu/pool/main/c/c-ares/libc-ares-dev_1.18.1-2ubuntu0.1_amd64.deb
        sudo apt-get install ./libc-ares2_1.18.1-2ubuntu0.1_amd64.deb ./libc-ares-dev_1.18.1-2ubuntu0.1_amd64.deb
        cd ${{ github.workspace }}

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-input-dir=${{ github.workspace }}/natives/src" >> "$GITHUB_OUTPUT"
        echo "build-output-dir=${{ github.workspace }}/natives/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ steps.strings.outputs.build-input-dir }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: natives-${{ matrix.artifact_classifier }}
        path: ${{ steps.strings.outputs.build-output-dir }}
